config/routes.rb
WayfarerLive::Application.routes.draw do
  resources :sales

  resources :memberships

  resources :journal_entries
  
  get '/buy', to: 'transactions#new', as: :show_buy
  post'/buy/:permalink', to:'transactions#create', as: :buy
  get'/pickup/:guid', to:'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  devise_scope :user do
    get 'users/new_nonks', to: "users/registrations#new_nonks", as: 'new_nonks'
    post 'create_nonks', to: "users/registrations#create_nonks"
  end
  
  
  get "pages/index"
  
  get '/users/:id', :to => 'users#show', :as => :user
  
  match '/journals', to: "journal_entries#index", via: :get
  match '/episodes', to: "pages#episodes", via: :get
  match '/about', to: "pages#about", via: :get
  match '/team', to: "pages#team", via: :get
  match '/get_access', to: "pages#get_access", via: :get
  match '/social_hub', to: "pages#social_hub", via: :get
  match '/header_iframe', to: "pages#header_iframe", via: :get
  match '/partners', to: "pages#partners", via: :get
  match '/contact_us', to: "pages#contact_us", via: :get
  match '/exclusive_content', to: "pages#exclusive_content", via: :get
  match '/event', to: "pages#event", via: :get
  match '/polls', to: "pages#polls", via: :get
  match '/access_levels', to: "pages#tiers", via: :get
  root to: "pages#index"

end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: [:show, :edit, :update, :destroy]

  # GET /journal_entries
  # GET /journal_entries.json
  def index
    @journal_entries = JournalEntry.all
  end

  # GET /journal_entries/1
  # GET /journal_entries/1.json
  def show
  end

  # GET /journal_entries/new
  def new
    @journal_entry = JournalEntry.new
  end

  # GET /journal_entries/1/edit
  def edit
  end

  # POST /journal_entries
  # POST /journal_entries.json
  def create
    @journal_entry = JournalEntry.new(journal_entry_params)

    respond_to do |format|
      if @journal_entry.save
        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @journal_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journal_entries/1
  # PATCH/PUT /journal_entries/1.json
  def update
    respond_to do |format|
      if @journal_entry.update(journal_entry_params)
        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_entries/1
  # DELETE /journal_entries/1.json
  def destroy
    @journal_entry.destroy
    respond_to do |format|
      format.html { redirect_to journal_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_entry_params
      params.require(:journal_entry).permit(:content, :title)
    end
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/journal_entries/_form.html.haml
.row
  .col-lg-8
    = form_for @journal_entry do |f|
      - if @journal_entry.errors.any?
        #error_explanation
          %h2= "#{pluralize(@journal_entry.errors.count, "error")} prohibited this journal_entry from being saved:"
          %ul
            - @journal_entry.errors.full_messages.each do |msg|
              %li= msg

      
      .form-group 
        = f.label :title, class: "control-label"
        = f.text_field :title, type: "text", class: "form-control", placeholder: "Don Quick-six"
      .form-group 
        = f.label :content, class: "control-label"
        = f.text_area :content, type: "text", rows: "5", class: "form-control", placeholder: "Dear Diary...."
      
      = f.submit 'Save', class: "btn btn-primary"

app/views/journal_entries/_journal_entry.html.haml
.journal-entry
  %h3 #{link_to journal_entry.title , journal_entry_path(journal_entry), class: "journal"}
  %p.journal-date #{journal_entry.created_at.strftime("%B %d, %Y")}
  / %p #{ truncate_with_link(journal_entry.content, 40, journal_entry_path(journal_entry)) }
  %p #{ truncate(journal_entry.content, 40) } #{link_to "Read More", journal_entry_path(journal_entry)}
  = render_shareable :buttons=> ['twitter', 'facebook', 'google_plus','reddit'] 

  -if current_user && current_user.admin?
    = link_to 'Edit', edit_journal_entry_path(journal_entry)
  

app/views/journal_entries/edit.html.haml
%h1 Editing journal_entry

= render 'form'

= link_to 'Show', @journal_entry
\|
= link_to 'Back', journal_entries_path

app/views/journal_entries/index.html.haml
.row
  .col-lg-3
  .col-lg-6.opaque-body
    %h1 Journals
    %h4 The crew’s stories from the road (beginning July 2nd)
    -if current_user && current_user.admin?
      =link_to "Add Journal entry", new_journal_entry_path
      %br/
      %br/
      / %table
      /   %tr
      /     %th Content
      /     %th
      /     %th
      /     %th
      / 
      /   - @journal_entries.each do |journal_entry|
      /     %tr
      /       %td= journal_entry.content
      /       %td= link_to 'Show', journal_entry
      /       %td= link_to 'Edit', edit_journal_entry_path(journal_entry)
      /       %td= link_to 'Destroy', journal_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }


    =render @journal_entries

app/views/journal_entries/new.html.haml
%h1 New Journal Entry

= render 'form'

app/views/journal_entries/show.html.haml
.row
  .col-lg-3
  .col-lg-6.opaque-body
    %p#notice= notice

    %h3 #{@journal_entry.title}
    %p.journal-date #{@journal_entry.created_at}
    %p #{simple_format h(@journal_entry.content)}

    = render_shareable

    /put rating system here

    #disqus_thread
    :javascript
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'wayfaring-live'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    %noscript
      Please enable JavaScript to view the
      %a{href: "http://disqus.com/?ref_noscript"} comments powered by Disqus.


    %a.dsq-brlink{href: "http://disqus.com"}
      comments powered by
      %span.logo-disqus Disqus


    -if current_user && current_user.admin?
      = link_to 'Edit', edit_journal_entry_path(@journal_entry)
  