config/routes.rb
WayfarerLive::Application.routes.draw do
  resources :sales

  resources :memberships

  resources :journal_entries
  
  get '/buy', to: 'transactions#new', as: :show_buy
  post'/buy/:permalink', to:'transactions#create', as: :buy
  get'/pickup/:guid', to:'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  devise_scope :user do
    get 'users/new_nonks', to: "users/registrations#new_nonks", as: 'new_nonks'
    post 'create_nonks', to: "users/registrations#create_nonks"
  end
  
  
  get "pages/index"
  
  get '/users/:id', :to => 'users#show', :as => :user
  
  match '/journals', to: "journal_entries#index", via: :get
  match '/episodes', to: "pages#episodes", via: :get
  match '/about', to: "pages#about", via: :get
  match '/team', to: "pages#team", via: :get
  match '/get_access', to: "pages#get_access", via: :get
  match '/social_hub', to: "pages#social_hub", via: :get
  match '/header_iframe', to: "pages#header_iframe", via: :get
  match '/partners', to: "pages#partners", via: :get
  match '/contact_us', to: "pages#contact_us", via: :get
  match '/exclusive_content', to: "pages#exclusive_content", via: :get
  match '/event', to: "pages#event", via: :get
  match '/polls', to: "pages#polls", via: :get
  match '/access_levels', to: "pages#tiers", via: :get
  root to: "pages#index"

end

app/views/pages/_header_iframe.html.haml
#header_iframe
  .container
    .nav-area.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container
        .row
          / Brand and toggle get grouped for better mobile display
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-header
            .col-lg-12
              %h4.title #{link_to "WF", "http://www.wayfaringlive.com/", :class => "title"}        


          / Collect the nav links, forms, and other content for toggling
          .navbar-collapse.collapse
            %ul.nav.navbar-nav 
              / %ul#nav_pill_section.nav.nav-pills.navbar-right.colored-pills 
              %li{:class => "#{'active' if current_page?('http://www.wayfaringlive.com')} smoothScroll"}=link_to "Home", "http://www.wayfaringlive.com/"
              %li{:class => "#{'active' if current_page?('http://www.wayfaringlive.com/about')} dropdown"}
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  About
                  %b.caret
                %ul.dropdown-menu
                  %li
                    =link_to "The Event", "http://www.wayfaringlive.com/about"
                  %li
                    =link_to "Team", "http://www.wayfaringlive.com/team"
              / %li{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/polls")}"}=link_to "Journals", "http://blog.wayfaringlive.com"
              %li{:class => "#{'active' if current_page?('http://www.wayfaringlive.com/journals')}"}=link_to "Journals", "http://www.wayfaringlive.com/journals"
              %li{:class => "#{'active' if current_page?('http://www.wayfaringlive.com/polls')}"}=link_to "Polls", "http://www.wayfaringlive.com/polls"
              %li{:class => "#{'active' if current_page?('http://www.wayfaringlive.com/social_hub')}"}=link_to "Social Hub", "http://www.wayfaringlive.com/social_hub"
              %li{:class => "#{'active' if current_page?(root_path)}"}=link_to "Shop", root_path

            
            / .nav.navbar-nav.navbar-right
            /          .user-nav
            /            
            /            -if user_signed_in?
            /              Cool Kid:
            /              -if current_user.email
            /                =link_to current_user.email, user_path(current_user), :class => "nav-user-link"
            /              -else
            /                =link_to "Your Page", user_path(current_user), :class => "nav-user-link"
            /              %i.icon.icon-user.nav-icon
            /              |
            /              =link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "#{'active' if current_page?(http://www.wayfaringlive.com/)} nav-user-signout nav-user-link"    
            /            -else
            /              Cool Kids:
            /              %i.icon.icon-user.nav-icon
            /              = link_to "Sign Up", new_user_registration_path, :class => "nav-user-link"
            /              or
            /              =link_to "Sign In", new_user_session_path, :class => "#{'active' if current_page?(http://www.wayfaringlive.com/)} nav-user-link" 
       

app/views/pages/about.html.haml
.row
  .col-lg-3
  .col-lg-6.opaque-body
    %h1 The Event
    %p Wayfaring is a first-of-its-kind docuseries event that follows host Malcolm Freberg and a film crew on a road trip around the United States. Our team is set to leave LA on July 1st and will complete a twenty-day loop of the country, ending back in southern California on July 20th. 

    %p During the trip, we’ll be producing a short episode every day -- meaning 20 episodes in 20 days this July, each available on the official Wayfaring site the day after it’s shot.

    %p Herein lies the rub:

    %p Our team doesn’t choose where we drive or what we do each day of the road trip; YOU do. Every major decision – what city to visit, what crazy stunt to attempt – is decided by a public vote via social media. For nearly three weeks this July, all Malcolm’s life choices will be dictated by you, the audience. 

    %p Wayfaring isn’t a show, it’s an event. Like a ‘Choose Your Own Adventure’ book, for twenty days YOU get to choose how this story progresses. Malcolm will fill in the gaps with his own special brand of nonsense, but never before has an audience had complete control over a living, breathing protagonist before. 

    %p This adventure isn’t just Malcolm’s – it’s yours as well.

app/views/pages/contact.html.haml
%h1 Contact Us
%p.italics Please keep in mind that our entire team, including web managers, are on the road from July 1 to July 20th, so our response may not be immediate. We will do our absolute best to get back to you in a timely fashion.

%p For all inquiries related to Wayfaring or Pink Guerrilla Productions:

pinkguerrilla@wayfaringlive.com

%p If you’re having issues with your Wayfaringlive.com account:

admin@wayfaringlive.com

%p Any other complaints or criticism:

eric.shinseki@hotmail.com

%p For all publicity inquiries, contact Mike Liotta at:

Mike@truepublicrelations.com


%p For information regarding Zoomph, visit:

www.Zoomph.com

app/views/pages/contact_us.html.haml
.row
  .col-lg-2
  .col-lg-8.opaque-body
    %h1 Contact Us
    %p.italics Please keep in mind that our entire team, including web managers, are on the road from July 1st to July 20th, so our response may not be immediate. We will do our absolute best to get back to you in a timely fashion.

    %br/
    %br/
    %p For all inquiries related to Wayfaring or Pink Guerrilla Productions: #{link_to 'pinkguerrilla@wayfaringlive.com', "mailto:pinkguerrilla@wayfaringlive.com"}

    %p If you’re having issues with your Wayfaringlive.com account: #{link_to 'admin@wayfaringlive.com', "mailto:admin@wayfaringlive.com"}


    %p Any other complaints or criticism: #{link_to 'eric.shinseki@hotmail.com', "mailto:eric.shinseki@hotmail.com"}


    %p For all press inquiries, contact Mike Liotta at: #{link_to 'Mike@truepublicrelations.com', "mailto:Mike@truepublicrelations.com"}



    %p For information regarding Zoomph, visit: #{link_to 'www.Zoomph.com', "http://www.Zoomph.com"}

app/views/pages/episodes.html.haml
.row
  .col-lg-2
  .col-lg-8.opaque-body
    %h1 Not yet!

    %p Full length episodes of Wayfaring begin July 2nd. In the meantime, #{link_to 'follow on Twitter', 'https://twitter.com/WayfaringLive'} for updates, preview footage, and teasers

app/views/pages/event.html.haml
.row
  .col-lg-3
  .col-lg-6.opaque-body
    %h1 The Event
    %p Wayfaring is a first-of-its-kind docuseries event that follows host Malcolm Freberg and a film crew on a road trip around the United States. Our team is set to leave LA on July 1st and will complete a twenty-day loop of the country, ending back in southern California on July 20th. 

    %p During the trip, we’ll be producing a short episode every day -- meaning 20 episodes in 20 days this July, each available on the official Wayfaring site the day after it’s shot.

    %p Herein lies the rub:

    %p Our team doesn’t choose where we drive or what we do each day of the road trip; YOU do. Every major decision – what city to visit, what crazy stunt to attempt – is decided by a public vote via social media. For nearly three weeks this July, all Malcolm’s life choices will be dictated by you, the audience. 

    %p Wayfaring isn’t a show, it’s an event. Like a ‘Choose Your Own Adventure’ book, for twenty days YOU get to choose how this story progresses. Malcolm will fill in the gaps with his own special brand of nonsense, but never before has an audience had complete control over a living, breathing protagonist before. 

    %p This adventure isn’t just Malcolm’s – it’s yours as well.

app/views/pages/exclusive_content.html.haml
.row
  .col-lg-2
  .col-lg-8.opaque-body.text-center
    .exclusive-content-upload
      %h1 Mini-teaser
      .video-container
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "360", :src => "//www.youtube.com/embed/QzZGzmZlNEA", :width => "640"}
    .exclusive-content-upload
      %h1 Welcome to the Rumpus!
      .video-container
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "563", :mozallowfullscreen => "", :src => "//player.vimeo.com/video/99389430", :webkitallowfullscreen => "", :width => "750"}
    
  .col-lg-2
    

app/views/pages/index.html.haml
.row.opaque-body
  .col-lg-8
    / %script{:charset => "utf-8", :src => "http://static.polldaddy.com/p/8132966.js", :type => "text/javascript"}
    / %noscript
    /   %a{:href => "http://polldaddy.com/poll/8132966/"} Where should we drive tomorrow?
    .video-container
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "360", :src => "//www.youtube.com/embed/Ds0gctCzo6Q", :width => "640"}
    %h1 #{link_to "First Exclusive Teaser Online Now! Click here for access", user_signed_in? ? exclusive_content_path : access_levels_path, class: "big-link"}

  .col-lg-4
    .twitter
      %a.twitter-timeline{"data-widget-id" => "471375252304326656", :href => "https://twitter.com/WayfaringLive"} Tweets by @WayfaringLive
      :javascript
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

  

app/views/pages/partners.html.haml
.row
  .col-lg-3
  .col-lg-6.opaque-body.text-center
    %h1 Products generously donated by:
    .row
      .col-lg-12
        %h2 AOL
        =image_tag 'aol.png', class: "partner-image"
    .row
      .col-lg-12
        %h2 Jansport
    
    .row
      .col-lg-12
        %h2 Kind
        =image_tag 'kind.jpg', class: "partner-image"
    
    .row
      .col-lg-12
        %h2 Vitafusion
  .col-lg-3

app/views/pages/polls.html.haml
/ %form{:action => "http://poll.pollcode.com/76443368", :method => "post"}
/   %table{:bgcolor => "EEEEEE", :border => "0", :cellpadding => "0", :cellspacing => "2", :width => "175"}
/     %tr
/       %td{:colspan => "2", :height => "10"}
/         %font{:color => "000000", :face => "Verdana", :size => "2"}
/           %b What are we going to eat for breakfast
/     %tr
/       %td{:width => "5"}
/         %input#76443368answer1{:name => "answer", :type => "radio", :value => "1"}/
/       %td
/         \&nbsp;
/         %font{:color => "000000", :face => "Verdana", :size => "2"}
/           %label{:for => "76443368answer1"} scorpion
/     %tr
/       %td{:width => "5"}
/         %input#76443368answer2{:name => "answer", :type => "radio", :value => "2"}/
/       %td
/         \&nbsp;
/         %font{:color => "000000", :face => "Verdana", :size => "2"}
/           %label{:for => "76443368answer2"} chorizo
/     %tr
/       %td{:width => "5"}
/         %input#76443368answer3{:name => "answer", :type => "radio", :value => "3"}/
/       %td
/         \&nbsp;
/         %font{:color => "000000", :face => "Verdana", :size => "2"}
/           %label{:for => "76443368answer3"} brains
/     %tr
/       %td{:colspan => "2", :height => "10"}
/         %center
/           %input{:type => "submit", :value => " Vote "}
/             \&nbsp;&nbsp;
/             %input{:name => "view", :type => "submit", :value => " View "}/
/     %tr
/       %td{:align => "right", :colspan => "2"}
/         %font{:color => "000000", :face => "Verdana", :height => "5", :size => "1"}
/           pollcode.com
/           = succeed "&amp;nbsp;" do
/             %a{:href => "http://pollcode.com/"}
/               %font{:color => "000000", :face => "Verdana", :size => "1"} free polls


.row
  .col-lg-1
  .col-lg-10.opaque-body
    %h1 Latest Poll
    / - Zoomph Polling Widget -
    /%iframe{:frameBorder => "0", :scrolling => "no", :src => "https://admin.zoomph.com/Display/Widget/v2/Polling.aspx?feedId=9858", :style => "height:391px; width:339px; border:none;"}

    / - Zoomph Polling Widget -


    


    / .wf-widget-wrap
    /   / Widget
    /   .zoomphWidget{"data-widgetId" => "FMt4K6a/yWA63qCJa9EcGPXPnEogVRwIVnnUGlXbSRgyZsAGmlYUJsby8p7lw52vhnlV+A=="}
    /   / END Widget
    /   / Footer Widget
    /   .wf-footer
    /     .wf-logo
    /       %img{:src => "//zoomphcontent.azurewebsites.net/clients/wayfaring/images/wf-footer-logo.png"}/
    /     .wf-zoomph-logo
    /       %a{:href => "//zoomph.com/", :target => "_blank"}
    /       %img{:src => "//zoomphcontent.azurewebsites.net/clients/wayfaring/images/wf-footer-zoomph-logo.png"}/
    /   / End Footer Widget

app/views/pages/shop.html.haml
%h2 We’re currently only selling access levels through Kickstarter
=link_to "Get Access!", "#", class: "btn btn-primary"

app/views/pages/social_hub.html.haml
/ / JS/CSS
/ %script{:src => "//display.zoomph.com/Scripts/jquery-1.7.1.min.js", :type => "text/javascript"}
/ %script{:src => "//display.zoomph.com/Bundles/socialHubLoader", :type => "text/javascript"}
/ .zoomphSocialHub{"data-socialHubId" => "araggZadcyqfe9TkNvODWUwnBG0SwcvUWfY32qBXEKXfKR+WorrwRNBZnzKySpsoVgSFOw=="}
.container
  / Zooomph Social Hub -
  .wf-twitter-btn
    .sb-tweet join the Conversation
    %a.twitter-hashtag-button{"data-related" => "wayfaringlive,wayfaringlive", "data-size" => "large", :href => "https://twitter.com/intent/tweet?button_hashtag=wayfaringlive"} Tweet #wayfaringlive
    :javascript
      !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');
  .zoomphSocialHub.opaque-body{"data-socialhubid" => "tqwaSKSg/tIxwRiIaakOcMvc7uZGZs7ESr7BXjNYayqnjc3BOOnohfXwmgP5fvJ0HBr/OA=="}

app/views/pages/team.html.haml
.row
  .col-lg-2
  .col-lg-8.opaque-body
    %h1 The Wayfaring Team
    .row
      .col-lg-6
        =image_tag 'Malcolm.jpg', class: "team-image"
      .col-lg-6
        %h3 Malcolm Freberg
        %p He truly believes this entertainment stuff is only temporary; he’s convinced one day he’ll be the captain of his own pirate spaceship.
    %br/
    .row
      .col-lg-6
        =image_tag 'Gorilla.jpg', class: "team-image"
      .col-lg-6
        %h3 The Gorilla
        %p [No information available]
    %br/
    .row
      .col-lg-6
        =image_tag 'Keetin.jpg', class: "team-image"
      .col-lg-6
        %h3 Keetin Marchi
        %P Keetin is a freelance television producer and entertainment host from Chapel HIll, NC who loves nothing more than cuddling with her puppy Ella and watching Game of Thrones or Say Yes to the Dress. She's hoping none of the boys wake up in jail or a ditch. 
    %br/
    .row
      .col-lg-6
        =image_tag 'Anh.jpg', class: "team-image"
      .col-lg-6
        %h3 Anh Phan
        %P Anh is a television industry professional from Boston who likes to play dodgeball in his spare time. He sometimes get car sick and his ultimate goal on this adventure is to make it through all twenty days without vomiting on Malcolm. He will fail.
    %br/
    .row
      .col-lg-6
        =image_tag 'Dylan.jpg', class: "team-image"
      .col-lg-6
        %h3 Dylan Cashbaugh
        %p Dylan is a midwestern boy who moved to the big city to make pictures. Well... something like that. He currently produces, shoots, and directs for web, television, and film audiences while living in West Hollywood. Dylan looks forward to filming Anh vomiting on Malcolm.
    %br/
    .row
      .col-lg-6
        =image_tag 'Chirstina.jpg', class: "team-image"
      .col-lg-6
        %h3 Christina Matthews
        %p Christina has a television production background and a ton of travel experience. Her greatest joy in life comes from planning Wayfaring events that terrify the entire crew.
    %br/
    .row
      .col-lg-6
        =image_tag 'Glenn.jpg', class: "team-image"
      .col-lg-6
        %h3 Glenn Rodriguez
        %p Glenn Rodriguez is a film editor originally from the “Real” Jersey Shore. When he isn’t working, you can find him watching New Jersey Devils hockey and cheesy horror flicks.
    %br/
    .row
      .col-lg-6
        =image_tag 'Matt.jpg', class: "team-image"
      .col-lg-6
        %h3 Matt Parent
        %p The man behind the camera: climber, photographer, camera operator, lover, magician, and king of awesome moves on the dance floor. The ladies...oh, how they swoon.
    %br/
    .row
      .col-lg-6
        =image_tag 'Elisa.jpg', class: "team-image"
      .col-lg-6
        %h3 Elisa Masso
        %p Elisa is a barefoot, animal loving hippy thats constantly traveling the world, doing yoga, humanitarian photography, and feeding hungry babies. When she's not saving the world she can be found at her local dive bar in San Diego drinking Fireball and winning goldfish races.
    %br/
    .row
      .col-lg-6
        =image_tag 'Interns.jpg', class: "team-image"
      .col-lg-6
        %h3 The Interns:
        %h4 Jack Heise, Brian Joseff, Keith Moffat, Michael Parets, Colin Skelly
        %p They’re only smiling because they don’t yet know what they’re about to be put through...

app/views/pages/tiers.html.haml
.opaque-body
  .row
    -if flash[:wrong_code]
      %h1.error=flash[:wrong_code]
    .col-lg-4.text-center
      %h2 Clown - #{formatted_price(@clown.price)}
      / =link_to "Get This!", new_user_registration_path(:tier_id => @clown.id)
      =link_to "Get This!", new_nonks_path(:tier_id => @clown.id), class: "btn btn-primary make-btn"
      %p exclusive content
    .col-lg-4.text-center
      %h2 Acrobat - #{formatted_price(@acrobat.price)}
      =link_to "Get This!", new_nonks_path(:tier_id => @acrobat.id), class: "btn btn-primary make-btn"
      %p exclusive content
      %p.bold.pop private polls
      
    .col-lg-4.text-center
      %h2 Fire Dancer - #{formatted_price(@fire_dancer.price)}
      =link_to "Get This!", new_nonks_path(:tier_id => @fire_dancer.id), class: "btn btn-primary make-btn"
      %p exclusive content
      %p private polls
      %p.bold.pop live Q&A
  .row
    %h3 Kickstarter backers: #{link_to "Sign up here", new_user_registration_path, class: "bright"}