config/routes.rb
WayfarerLive::Application.routes.draw do
  resources :sales

  resources :memberships

  resources :journal_entries
  
  get '/buy', to: 'transactions#new', as: :show_buy
  post'/buy/:permalink', to:'transactions#create', as: :buy
  get'/pickup/:guid', to:'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  devise_scope :user do
    get 'users/new_nonks', to: "users/registrations#new_nonks", as: 'new_nonks'
    post 'create_nonks', to: "users/registrations#create_nonks"
  end
  
  
  get "pages/index"
  
  get '/users/:id', :to => 'users#show', :as => :user
  
  match '/journals', to: "journal_entries#index", via: :get
  match '/episodes', to: "pages#episodes", via: :get
  match '/about', to: "pages#about", via: :get
  match '/team', to: "pages#team", via: :get
  match '/get_access', to: "pages#get_access", via: :get
  match '/social_hub', to: "pages#social_hub", via: :get
  match '/header_iframe', to: "pages#header_iframe", via: :get
  match '/partners', to: "pages#partners", via: :get
  match '/contact_us', to: "pages#contact_us", via: :get
  match '/exclusive_content', to: "pages#exclusive_content", via: :get
  match '/event', to: "pages#event", via: :get
  match '/polls', to: "pages#polls", via: :get
  match '/access_levels', to: "pages#tiers", via: :get
  root to: "pages#index"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :sale
  
  before_create :populate_guid
  
  private
  def populate_guid
    self.guid = SecureRandom.uuid()
  end
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:email, :guid, :product_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, "error")} prohibited this sale from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :guid
    = f.text_field :guid
  .field
    = f.label :product
    = f.text_field :product
  .actions
    = f.submit 'Save'

app/views/sales/edit.html.haml
%h1 Editing sale

= render 'form'

= link_to 'Show', @sale
\|
= link_to 'Back', sales_path

app/views/sales/index.html.haml
%h1 Listing sales

%table
  %tr
    %th Email
    %th Guid
    %th Product
    %th
    %th
    %th

  - @sales.each do |sale|
    %tr
      %td= sale.email
      %td= sale.guid
      %td= sale.product
      %td= link_to 'Show', sale
      %td= link_to 'Edit', edit_sale_path(sale)
      %td= link_to 'Destroy', sale, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sale', new_sale_path

app/views/sales/new.html.haml
%h1 New sale

= render 'form'

= link_to 'Back', sales_path

app/views/sales/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @sale.email
%p
  %b Guid:
  = @sale.guid
%p
  %b Product:
  = @sale.product

= link_to 'Edit', edit_sale_path(@sale)
\|
= link_to 'Back', sales_path