config/routes.rb
WayfarerLive::Application.routes.draw do
  resources :sales

  resources :memberships

  resources :journal_entries
  
  get '/buy', to: 'transactions#new', as: :show_buy
  post'/buy/:permalink', to:'transactions#create', as: :buy
  get'/pickup/:guid', to:'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  
  devise_scope :user do
    get 'users/new_nonks', to: "users/registrations#new_nonks", as: 'new_nonks'
    post 'create_nonks', to: "users/registrations#create_nonks"
  end
  
  
  get "pages/index"
  
  get '/users/:id', :to => 'users#show', :as => :user
  
  match '/journals', to: "journal_entries#index", via: :get
  match '/episodes', to: "pages#episodes", via: :get
  match '/about', to: "pages#about", via: :get
  match '/team', to: "pages#team", via: :get
  match '/get_access', to: "pages#get_access", via: :get
  match '/social_hub', to: "pages#social_hub", via: :get
  match '/header_iframe', to: "pages#header_iframe", via: :get
  match '/partners', to: "pages#partners", via: :get
  match '/contact_us', to: "pages#contact_us", via: :get
  match '/exclusive_content', to: "pages#exclusive_content", via: :get
  match '/event', to: "pages#event", via: :get
  match '/polls', to: "pages#polls", via: :get
  match '/access_levels', to: "pages#tiers", via: :get
  root to: "pages#index"

end

app/views/layouts/_header.html.haml
%nav.navbar.nav-area.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .row
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{ type: "button", "data-toggle" => "collapse", "data-target" => "#wayfaring_nav"}
          / %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .header-logo
          =link_to "", root_path
      / Collect the nav links, forms, and other content for toggling
      #wayfaring_nav.collapse.navbar-collapse
        %ul.nav.navbar-nav 
          / %ul#nav_pill_section.nav.nav-pills.navbar-right.colored-pills 
          /%li{:class => "#{'active' if current_page?(root_path)} smoothScroll"}=link_to "Home", root_path
          %li{:class => "#{'active' if current_page?(episodes_path)}"}=link_to "Episodes", episodes_path
          %li{:class => "#{'active' if current_page?(about_path)} dropdown"}
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              About
              %b.caret
            %ul.dropdown-menu
              %li
                =link_to "The Event", about_path
              %li
                =link_to "Team", team_path
              %li
                =link_to "Partners", partners_path
              %li
                =link_to "Contact Us", contact_us_path
          %li{:class => "#{'active' if current_page?(journals_path)}"}=link_to "Journals", journals_path
          %li{:class => "#{'active' if current_page?(social_hub_path)}"}=link_to "Social Hub", social_hub_path
          %li{:class => "#{'active' if current_page?(exclusive_content_path)}"}=link_to "Exclusive Content", current_user ? exclusive_content_path : access_levels_path
          -unless user_signed_in?
            %li#nav-pill-pink{:class => "#{'active' if current_page?(get_access_path)}"}=link_to "Get Access", access_levels_path
          
          / %li{:class => "#{'active' if current_page?(exclusive_content_path)}"}=link_to "Join the Rumpus", exclusive_content_path
          / 
          
          /// ACTIVATE WHEN KICKSTARTER IS LIVE

          -if user_signed_in?
            %li
              =link_to "Sign out", destroy_user_session_path, :method => :delete
          -else  
            %li{:class => "#{'active' if current_page?(about_path)} dropdown"}
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}        
                Join the Rumpus
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Sign Up", new_user_registration_path
                %li
                  =link_to "Sign In", new_user_session_path
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wayfaring
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application"
    / %link{:href => 'http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css', :rel => "stylesheet", :type => "text/css"}
    %meta{:name=>"description", :content=> "The 20-day interactive road trip hosted by Malcolm Freberg. See latest episodes, meet the crew, view exclusive content, and more."}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    = tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY
    / Zoomph Head Code
    /%script{:src => "//display.zoomph.com/Scripts/jquery-1.7.1.min.js", :type => "text/javascript"}
    %script{:src => "//display.zoomph.com/Bundles/socialHubLoader", :type => "text/javascript"}
    %link{:href => "//zoomphcontent.azurewebsites.net/clients/wayfaring/Style-socialhub.css", :rel => "stylesheet"}/
    / END Zoomph Head Code
    / -- ZOOMPH JS/CSS (Needed once per page)
    %script{:src => "//display.zoomph.com/Bundles/widgetLoader", :type => "text/javascript"}
    %link{:href => "//display.zoomph.com/Bundles/widgetCss", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//admin.zoomph.com/Display/Widget/v5/Styles/Reset.css", :rel => "stylesheet"}/
    %link{:href => "//zoomphcontent.azurewebsites.net/clients/wayfaring/style.css", :rel => "stylesheet"}
    / -- END ZOOMPH JS/CSS (Needed once per page)
    
    / -- JS/CSS (Needed once per page)
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}
    %link{:href => "/favicon.ico", :rel => "icon", :type => "image/x-icon"}/
    %script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
    
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-51824506-1', 'wayfaringlive.com');
      ga('send', 'pageview');
    = csrf_meta_tags
  /%body{class: "#{'normal' if !current_page?(header_iframe_path)}"}
  %body.normal
    .container
      %p.notice #{notice}
      %p.alert  #{alert}
      -if flash[:success]
        %h1.success #{flash[:success]}
      =render "layouts/header"
    .container
      .opaque-bodyx
        = yield
        = debug(params) if Rails.env.development?
  %footer

app/views/layouts/header_iframe.html.haml
.container
  .nav-area.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container
      .row
        / Brand and toggle get grouped for better mobile display
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-header
          .col-lg-12social_hub_path
            %h4.title #{link_to "WF", "http://www.wayfaringlive.com/", :class => "title"}        


        / Collect the nav links, forms, and other content for toggling
        .navbar-collapse.collapse
          %ul.nav.navbar-nav 
            / %ul#nav_pill_section.nav.nav-pills.navbar-right.colored-pills 
            %li{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/")} smoothScroll"}=link_to "Home", "http://www.wayfaringlive.com/"
            %li{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/about")} dropdown"}
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                About
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "The Event", "http://www.wayfaringlive.com/about"
                %li
                  =link_to "Team", "http://www.wayfaringlive.com/team"
            / %li{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/polls")}"}=link_to "Journals", "http://blog.wayfaringlive.com"
            %li{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/journals")}"}=link_to "Journals", "http://www.wayfaringlive.com/journals"
            %li#nav-pill-pink{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/polls)"}"}=link_to "Polls", "http://www.wayfaringlive.com/polls"
            %li#nav-pill-pink{:class => "#{'active' if current_page?("http://www.wayfaringlive.com/social_hub")}"}=link_to "Social Hub", "http://www.wayfaringlive.com/social_hub"
            %li#nav-pill-pink{:class => "#{'active' if current_page?(root_path)}"}=link_to "Shop", root_path

            
          / .nav.navbar-nav.navbar-right
          /          .user-nav
          /            
          /            -if user_signed_in?
          /              Cool Kid:
          /              -if current_user.email
          /                =link_to current_user.email, user_path(current_user), :class => "nav-user-link"
          /              -else
          /                =link_to "Your Page", user_path(current_user), :class => "nav-user-link"
          /              %i.icon.icon-user.nav-icon
          /              |
          /              =link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "#{'active' if current_page?(http://www.wayfaringlive.com/)} nav-user-signout nav-user-link"    
          /            -else
          /              Cool Kids:
          /              %i.icon.icon-user.nav-icon
          /              = link_to "Sign Up", new_user_registration_path, :class => "nav-user-link"
          /              or
          /              =link_to "Sign In", new_user_session_path, :class => "#{'active' if current_page?(http://www.wayfaringlive.com/)} nav-user-link" 
       